Repository HanaFun/HanaFun_FE, pull requests merged in 2024-07, with the labels that each got.

#34 [Feat/#31] merge 후 수정사항
  public/images/hanaMain/bankbook.png
  src/App.tsx
  src/components/common/Navbar.tsx
  src/components/molecules/Alarm.tsx
  src/components/molecules/Ex.tsx
  src/components/molecules/HanaMainCard.tsx
  src/components/molecules/LessonDateChoice.tsx
  src/components/molecules/QR.tsx
  src/components/organisms/Ex.tsx
  src/hooks/ex.ts
  src/hooks/useTimer.tsx
  src/main.tsx
  src/pages/main/HanaFunMain.tsx
  src/pages/main/HanaMain.tsx
  src/pages/openLesson/RegisterLesson.tsx
  src/pages/search/PayLesson.tsx
  src/utils/scrollToTop.ts
Labels: 오류수정, 기능구현, 퍼블리싱

#37 [Feat/#35] 공통 api 연결
  src/apis/apiClient.ts
  src/apis/interfaces/lessonApi.ts
  src/apis/interfaces/reservationApi.ts
  src/apis/interfaces/userApi.ts
  src/apis/interfaces/usersApi.ts
  src/apis/url.ts
  src/components/common/Topbar.tsx
  src/components/molecules/HostLessonInfo.tsx
  src/components/molecules/LessonDetail.tsx
  src/components/molecules/LessonList.tsx
  src/components/molecules/MyCalendar.tsx
  src/components/molecules/UserInfo.tsx
  src/components/organisms/HostLessonSlider.tsx
  src/pages/main/HanaFunMain.tsx
  src/pages/mypage/HostLessonCalendar.tsx
  src/pages/mypage/HostPage.tsx
  src/pages/mypage/LessonCalendar.tsx
  src/pages/mypage/MyPage.tsx
  src/types/hostLessonDetail.d.ts
  src/types/hostLessonInfo.d.ts
  src/types/lesson.d.ts
  src/types/reservation.d.ts
  src/types/response.d.ts
  src/types/user.d.ts
Labels: 기능구현

#39 [Feat/#36] 로그인, 메인(계좌, 인기클래스), QR 결제 api 연동
  src/apis/apiClient.ts
  src/apis/interfaces/accountApi.ts
  src/apis/interfaces/categoryApi.ts
  src/apis/interfaces/hostApi.ts
  src/apis/interfaces/transactionApi.ts
  src/apis/interfaces/userApi.ts
  src/components/Atom/InputMoney.tsx
  src/components/common/Modal.tsx
  src/components/molecules/PopularLessonItem.tsx
  src/components/molecules/QR.tsx
  src/components/organisms/AccountPwKeypad.tsx
  src/components/organisms/ChoiceAccount.tsx
  src/constants/accountSliderOver3Settings.ts
  src/constants/accountSliderUnder2Settings.ts
  src/constants/introCardSliderSettings.ts
  src/index.css
  src/pages/auth/Login.tsx
  src/pages/main/HanaFunMain.tsx
  src/pages/main/QRPay.tsx
  src/pages/openLesson/RegisterHost.tsx
  src/pages/search/PayLesson.tsx
  src/types/account.d.ts
  src/types/category.d.ts
  src/types/error.d.ts
  src/types/host.d.ts
  src/types/lesson.d.ts
  src/types/reservation.d.ts
  src/types/transaction.d.ts
  src/types/user.d.ts
Labels: 기능구현

#42 [Feat/#38] 마이페이지 출력, 나의 신청 클래스 출력, 클래스 예약 취소, 신청 클래스 일정, 예약자 정보, 환불 api 연결
  src/apis/apiClient.ts
  src/apis/interfaces/reservationApi.ts
  src/apis/interfaces/transactionApi.ts
  src/apis/url.ts
  src/components/molecules/ApplicantInfo.tsx
  src/components/molecules/LessonDetail.tsx
  src/components/molecules/LessonList.tsx
  src/components/organisms/ApplicantList.tsx
  src/components/organisms/LessonSlider.tsx
  src/pages/main/HanaFunMain.tsx
  src/pages/mypage/HostLessonCalendar.tsx
  src/pages/mypage/LessonCalendar.tsx
  src/pages/mypage/MyLessonList.tsx
  src/pages/mypage/MyPage.tsx
  src/types/commonLesson.d.ts
  src/types/lesson.d.ts
  src/types/myLesson.d.ts
  src/types/reservation.d.ts
  src/types/transaction.d.ts
Labels: 기능구현

#46 [Feat/#41] 전체 매출액, 월별 매출액, 클래스별 연간 매출액, 지출액 수정 api 연결
  src/apis/apiClient.ts
  src/apis/interfaces/revenueApi.ts
  src/components/molecules/Calculator.tsx
  src/components/molecules/EditPrice.tsx
  src/components/molecules/LineChart.tsx
  src/components/molecules/PieChart.tsx
  src/components/molecules/TotalSales.tsx
  src/components/molecules/TotalSalesCard.tsx
  src/components/organisms/LessonSalesList.tsx
  src/pages/main/HanaFunMain.tsx
  src/pages/mypage/Sales.tsx
  src/pages/mypage/SalesYear.tsx
  src/types/revenue.d.ts
Labels: 기능구현

#45 [Feat/#44] 클래스 개설, 호스트 등록 api 연동, QR 결제 api 수정
  src/apis/apiClient.ts
  src/apis/imageApiClient.ts
  src/apis/interfaces/lessonApi.ts
  src/apis/interfaces/reservationApi.ts
  src/components/molecules/AddLessonTimeList.tsx
  src/components/molecules/SelectAddress.tsx
  src/constants/hostMain.ts
  src/pages/main/HanaFunMain.tsx
  src/pages/main/Home.tsx
  src/pages/main/QRPay.tsx
  src/pages/openLesson/OpenLessonMain.tsx
  src/pages/openLesson/RegisterHost.tsx
  src/pages/openLesson/RegisterLesson.tsx
  src/pages/search/LessonDetail.tsx
  src/pages/search/LessonSearch.tsx
  src/types/host.d.ts
  src/types/lesson.d.ts
  src/types/transaction.d.ts
Labels: 기능구현

#49 [Fix/#47] 예외 처리
  src/components/molecules/MyCalendar.tsx
  src/components/organisms/HostLessonSlider.tsx
  src/components/organisms/LessonSlider.tsx
  src/pages/mypage/HostLessonCalendar.tsx
  src/pages/mypage/HostPage.tsx
  src/pages/mypage/LessonCalendar.tsx
  src/pages/mypage/MyPage.tsx
  src/types/lesson.d.ts
Labels: 오류수정

#52 [Fix/#50] 예외 처리
  src/components/molecules/LessonDetail.tsx
  src/components/molecules/MyCalendar.tsx
  src/pages/mypage/LessonCalendar.tsx
  src/pages/mypage/SalesYear.tsx
Labels: 오류수정

#53 [Fix/#48] 예외처리(토큰 만료, 라우터 결제로 안넘어가게)
  src/apis/apiClient.ts
  src/components/molecules/LessonDateChoice.tsx
  src/components/molecules/PopularLessonItem.tsx
  src/main.tsx
  src/pages/main/HanaFunMain.tsx
  src/pages/main/QRPay.tsx
  src/pages/openLesson/RegisterHost.tsx
  src/pages/openLesson/RegisterLesson.tsx
  src/pages/search/LessonDetail.tsx
  src/pages/search/PayLesson.tsx
Labels: 오류수정

#56 [Fix/#55] 오류 수정
  src/apis/apiClient.ts
  src/components/molecules/AddLessonInput.tsx
  src/components/molecules/AddLessonTimeList.tsx
  src/components/molecules/PasswordKeypad.tsx
  src/components/molecules/QRScanner.tsx
  src/index.css
  src/pages/main/HanaFunMain.tsx
  src/pages/search/LessonDetail.tsx
Labels: 오류수정
